log:
  exp_name: vase
  eval_only: true
render:
  eval_grid_size: 1200
guide:
  shape_path: data/mesh/vase/vase.obj
  initial_texture: data/mesh/vase/textures/Image_0.png
  texture_resolution: 1024
optim:
  seed: 3
