log:
  exp_name: vase_train
render:
  eval_grid_size: 1200
guide:
  shape_path: data/mesh/vase/vase.obj
  mat2im_path: experiments/vase/gpt4_query/result_mat2im.json
  result_path: experiments/vase/results
  texture_resolution: 1024
optim:
  seed: 3
